name: Generate Release Notes

on:
  pull_request:
    paths:
      - 'openapi.yaml' # Adjust this to the path of your OpenAPI file

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install gitpython pyyaml deepdiff

      - name: Run Release Notes Generation Script
        run: python generate_release_notes.py

      # Optional: Commit and push the release notes file
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add RELEASE_NOTES.md
          git commit -m "Update release notes"
          git push
